version: 0.2

phases:
  pre_build:
    commands:
      - echo Connecting to Amazon ECS...
      - aws --version
      - $(aws ecr get-login --region ap-northeast-1 --no-include-email)
      - REPOSITORY_URI=730335414799.dkr.ecr.us-east-1.amazonaws.com/nestjs_ecs
      - COMMIT_HAST=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
    build:
      commands:
        - echo Build started on `date`
        - echo Building the Docker image...
        - docker build -t REPOSITORY_URI:latest .
        - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
      post_build:
        - echo Build completed on `date`
        - echo Pushing the docker image
        - docker push $REPOSITORY_URI:latest
        - docker push $REPOSITORY_URI:$IMAGE_TAG
        - echo Writing image definition file...
        - printf '[{"name":"nestjs_ecs-deploy","imageUri":"%s"}]'
          $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
        - cat imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
      